config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
  get 'session/new'
  get 'session/create'
  get 'session/destroy'
  root 'main#index'
  get 'main/index'
  get 'main/edit'
  get 'main/destroy'
  get 'main/create'
  post 'main/create'
  patch 'main/create'
  get 'profile/:id', to: 'main#profile'
  get 'likers/:id', to: 'main#likers'
  get 'search/:group', to: 'main#search'
  get 'faculty/:faculty', to: 'main#faculty'
  get 'main/my_profile'
  get 'records/:id', to: 'wall#records'
  get '/signin', to: 'session#new'
  get '/signup', to: 'users#new'
  get '/signout', to: 'session#destroy'
  get 'session/destroy'
  get 'love', to: 'main#love_users'
  get 'records/:id', to: 'wall#records'
  get '/edit_record/', to: 'wall#edit_record'
  get 'wall/delete_record'
  get 'wall/update'
  post 'wall/update'
  patch 'wall/update'
  get '/add_record', to: 'wall#add_record'
  get 'wall/create_record'
  post 'wall/create_record'
  patch 'wall/create_record'
  get 'main/add'
  get 'main/delete'
  get 'main/delete_card'

  resources :session, only: %i[new create destroy]
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
end

app/controllers/main_controller.rb
# frozen_string_literal: true

# All logic
class MainController < ApplicationController
  before_action :set_user, only: %i[index my_profile edit create destroy
                                    love_users search likers profile search faculty add delete_card delete]
  def index
    all_persons = User.all.order(:id).reverse_order
    if @_current
      @persons = []
      all_persons.find_each do |person|
        @persons << person unless UserCommunication.find_by_liker_and_like(@_current.id, person.id)
      end
      @persons = @persons.reverse
    else
      @persons = all_persons
    end
  end

  def my_profile; end

  def profile
    id = params[:id].to_i
    if id.to_s =~ /\A[0-9]+\Z/
      if (@man = User.find_by_id(id))
      else
        render :error
      end
    else
      render :error
    end
  end

  def edit; end

  def create
    if !request.get?
      current_user
      if @_current.update(user_params)
        redirect_to main_my_profile_path
      else
        render :edit
      end
    else redirect_to main_edit_path
    end
  end

  def love_users
    all_id = []
    UserCommunication.where(liker: @_current.id).find_each do |communication|
      all_id << communication.like
    end
    @all_users = all_id.map { |current_id| User.find_by_id(current_id) }
  end

  def destroy
    UserCommunication.where(like: @_current.id).find_each(&:destroy)
    UserCommunication.where(liker: @_current.id).find_each(&:destroy)
    @_current.destroy
    redirect_to root_url
  end

  def add
    @kogo = params[:kogo]
    kto = @_current.id
    comm = UserCommunication.new
    comm.liker = kto
    comm.like = @kogo
    if comm.save
      respond_to do |format|
        format.js
      end
    else
      render :error
    end
  end

  def delete
    @kogo = params[:kogo]
    delete_communication(@kogo, @_current.id)
    respond_to do |format|
      format.js
    end
  end

  def delete_card
    @kogo = params[:kogo]
    delete_communication(@kogo, @_current.id)
    respond_to do |format|
      format.js
    end
  end

  def likers
    id = params[:id].to_i
    if id.to_s =~ /\A[0-9]+\Z/
      if (@user = User.find_by_id(id))
        all_id = []
        UserCommunication.where(like: id).find_each do |communication|
          all_id << communication.liker
        end
        @persons = all_id.map { |current_id| User.find_by_id(current_id) }
      else
        render :error
      end
    else
      render :error
    end
  end

  def search
    @group = params[:group]
    if @group.to_s =~ /(\A((ИУ)|(СМ)|(МТ)|(РК)|(СГН)|(БМТ)|(ИБМ)|(АК)|(ИСОТ)|(ОЭ)|(РКТ)|(РТ)|(Э)|(ЮР)|(ФН)|(РЛ))((1[0-2])|[1-9])-((1[0-2])|[1-9])[1-9](А|Б|М)?\Z)/
      @persons = User.where(group: @group)
    else
      render :error
    end
  end

  def faculty
    @faculty = params[:faculty]
    if @faculty.to_s =~ /(\A((ИУ)|(СМ)|(МТ)|(РК)|(СГН)|(БМТ)|(ИБМ)|(АК)|(ИСОТ)|(ОЭ)|(РКТ)|(РТ)|(Э)|(ЮР)|(ФН)|(РЛ))((1[0-2])|[1-9])\Z)/
      @persons = User.where('"group" like ?', @faculty + '%')
    else
      render :error
    end
  end

  private

  def delete_communication(kogo, kto)
    communication_to_delete = UserCommunication.find_by_like_and_liker(kogo, kto)
    communication_to_delete.destroy
  end

  def user_params
    params.require(:user).permit(:email, :password, :first_name, :last_name, :city, :town,
                                 :status, :info, :group, :born, :contact, :avatar, :love_status)
  end

  def set_user
    @_current = User.find_by_id(session[:current_user_id])
  end
end

app/helpers/main_helper.rb
# frozen_string_literal: true

module MainHelper
end

app/views/main/_ list.html.erb
<% @persons.each do |person| %>
  <% if person %>
<div class="col-9 ">
  <div class="row question-box">
    <div class="col-3 a">
      <% if person.avatar.file.nil?%>
      <img src="/assets/def_avatar.jpg" class="question-img" alt= "<%=t 'avatar'%>">
      <% else %>
      <%= image_tag person.avatar.url, :class => "question-img", :alt => "Аватар"%>
      <% end %>
    </div>
    <div class="col-9 a">
      <% if !@_current || @_current.id != person.id %>
      <div class="question-title a"><a class="text-dark" href="../profile/<%= person.id %>"><%= person.first_name %> <%= person.last_name %>  </a></div>
      <% else %>
      <div class="question-title a"><a class="text-dark" href="../<%= I18n.locale %>/main/my_profile"><%= person.first_name %> <%= person.last_name %>  </a></div>
      <% end %>
      <span class="question-text a" ><%= person.status %> </span>
      <br/><br>
      <a href="/<%= I18n.locale %>/search/<%= person.group %>"> <span class="question-text a"><%= person.group %> </span> </a>
      <div class="row">
        <div class="col-5 a">
        </div>
        <% if @_current %>
        <div class="nrav">
          <% if !@_current || @_current.id != person.id %>
          <% if UserCommunication.find_by_liker_and_like(@_current.id, person.id) %>
          <%= link_to image_tag(image_path('сердце3.svg'), class: "mini"), main_add_path(params: { kto:@_current.id, kogo:person.id }), remote: true, id: "add_#{person.id}", class: "mini_a"%>
          <%= link_to  image_tag(image_path('разбито1.jpg'), class: "mini2"), main_delete_path(params: { kto:@_current.id, kogo:person.id }), remote: true,  id: "dis_#{person.id}"%>
          <% else %>
          <%= link_to image_tag(image_path('сердце3.svg'), class: "mini"), main_add_path(params: { kto:@_current.id, kogo:person.id }), remote: true, id: "add_#{person.id}"%>
          <%= link_to  image_tag(image_path('разбито1.jpg'), class: "mini2"), main_delete_path(params: { kto:@_current.id, kogo:person.id }), remote: true,  id: "dis_#{person.id}", class: "mini_a"%>
          <% end %>
          <a href="../likers/<%= person.id %>"><span id="like_<%= person.id %>" class="number_like"><%= UserCommunication.where(like: person.id).count %></span></a>
          <% else %>
          <% end %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<%end %>
<% end %>

app/views/main/add.js.erb
num = document.getElementById('like_<%= @kogo %>')
num.style.color = "red";
num.textContent = Number(num.textContent) +1;
like = document.getElementById('add_<%= @kogo %>')
like.style.display = "none"
dislike = document.getElementById('dis_<%= @kogo %>')
dislike.style.display = "inline"

app/views/main/delete.js.erb
num = document.getElementById('like_<%= @kogo %>')
num.style.color = "#2E2F30";
num.textContent = Number(num.textContent) - 1;
dislike = document.getElementById('dis_<%= @kogo %>')
dislike.style.display = "none"
like = document.getElementById('add_<%= @kogo %>')
like.style.display = "inline"

app/views/main/delete_card.js.erb
elem_to_del = document.getElementById('<%= @kogo %>')
elem_to_del.remove()

app/views/main/edit.html.erb
<div  class ="sign_form">
  <% if @_current.errors.any? %>
  <div id="error_explanation">
    <h2> <%=t 'from_being_saved'%> </h2>
    <ul>
      <% @_current.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <%=  form_with(model:@_current,  local: true, url: main_create_path, :class => 'form_ed') do |form|%>
  <h1 class="vb"> <img id="logo" src="/assets/сердце3.svg" />VBomonke</h1><br/>
  <%= form.text_field :first_name, :class => 'form-control inp em',:placeholder => t('sername') %>
  <%= form.text_field :last_name, :class => 'form-control inp' ,:placeholder => t('name') %>
  <%= form.text_field :group, :class => 'form-control inp' ,:placeholder => t('group_plhldr') %>
  <%= form.date_field :born, :class => 'form-control inp' %>
  <%= form.text_field :status, :class => 'form-control inp' ,:placeholder => t('prof_status') %>
  <%= form.email_field :email, :class => 'form-control inp',:placeholder => t('email')%>
  <%= form.text_field :love_status, :class => 'form-control inp' ,:placeholder => t('status') %>
  <%= form.text_field :city, :class => 'form-control inp' ,:placeholder => t('country') %>
  <%= form.text_field :town, :class => 'form-control inp' ,:placeholder => t('point') %>
  <%= form.text_field :contact, :class => 'form-control inp' ,:placeholder => t('vk')  %>
  <%= form.text_area :info, :class => 'form-control inp' ,:placeholder => t('info')  %>
  <%= form.password_field :password, :class => 'form-control inp psr',:placeholder => t('pass')%>
  <% if @_current.avatar.file.nil?%>
  <% else %>
  <%= image_tag @_current.avatar.url, :class => "question-img avatarka", :alt => t('avatar') %>
  <% end %>
  <%= form.file_field :avatar, :class => 'form-control inp'  %>
  <%= form.submit t('edit_link') , :class => 'btn btn-outline-secondary'   %>
  <span class="link_to_sign"><%=t 'think' %></span>
  <%= link_to t('back_link'), main_my_profile_path %>
  <br><br>
  <%= link_to  t('delete'), main_destroy_path,
  data: { confirm: t('delete_confirm') }, :class => "link_to" %>
  <% end %>
</div>

app/views/main/error.html.erb
<span>ТЫ ЧТО БАЛУЕШЬСЯ, ДУРАЧОК</span>

app/views/main/faculty.html.erb
<div class="container">
  <div id="main">
    <header class="hea">
      <nav class="navbar navbar-expand-md fixed-top">
        <img id="logo" src="/assets/сердце3.svg">
        <a class="navbar-brand text-dark site_name" href="../../<%= I18n.locale %>/">VBomonke</a>
        <div class="collapse navbar-collapse" id="navbarCollapse">
        </div >
        <div id="but">
          <a href= "../../<%= I18n.locale %>/main/my_profile"> <button type="button" class="btn btn-outline-secondary"><%=t 'my_profile'%><%= @_current.last_name %></button></a>
        </div>
      </nav>
    </header>
    <% if @persons.length==0 %>
    <span id="new"><%=t 'begin_mess'%><%= @faculty %>  <%=t 'end_mass'%></span>
    <% else %>
    <span id="new"><%=t 'direction'%> <%= @faculty %></span>
    <% end %>
    <%= render 'main/ list' %>
  </div>
</div>

app/views/main/index.html.erb
<div class="container">
  <div id="main">
    <header class="hea">
      <nav class="navbar navbar-expand-md fixed-top">
        <img id="logo" src="/assets/сердце3.svg">
        <a class="navbar-brand text-dark site_name" href="#">VBomonke</a>
        <div class="collapse navbar-collapse" id="navbarCollapse">
        </div >
        <div id="but">
          <% if @_current %>
          <a href="../signout"><button type="button" id="exit" class="btn btn-outline-secondary"><%=t 'output'%></button></a>
          <a href= "/<%= I18n.locale %>/main/my_profile"> <button type="button" id="prof" class="btn btn-outline-secondary"><%=t 'my_profile'%> <%= @_current.last_name %></button></a>
          <%else %>
          <a href="../signin"><button type="button" id="entre" class="btn btn-outline-secondary"  ><%=t 'entry'%></button></a>
          <a href="../signup"> <button type="button" id="reg" class="btn btn-outline-secondary"><%=t 'registration'%></button></a>
          <% end %>
        </div>
        <div class="language">
          <% if params[:locale] == "en" %>
          <span>
              <%= link_to "Рус", { locale: :ru },class: "nav-link" %>
          </span>
            <span>
            <%= link_to "En", { locale: :en },class: "nav-link",:style=>'color: red;' %>
          </span>
            <% else %>
            <span>
              <%= link_to "Рус", { locale: :ru },class: "nav-link",:style=>'color: red;' %>
          </span>
            <span >
            <%= link_to "En", { locale: :en },class: "nav-link"%>
          </span>
              <% end %>
        </div>
      </nav>
    </header>
    <% if @persons.length==0 %>
    <span id="new"><%=t 'no_users'%></span>
    <% else %>
    <span id="new"><%=t 'New_users'%></span>
    <% end %>
    <% @persons.each do |person| %>
    <% if !@_current || @_current.id != person.id %>
    <div class="col-9 ">
      <div class="row question-box">
        <div class="col-3 a">
          <% if person.avatar.file.nil?%>
          <img src="/assets/def_avatar.jpg" class="question-img"alt="<%=t 'avatar'%>">
          <% else %>
          <%= image_tag person.avatar.url, :class => "question-img", :alt => "Аватар"%>
          <% end %>
        </div>
        <div class="col-9 a">
          <div class="question-title a"><a class="text-dark" href="../<%= I18n.locale %>/profile/<%= person.id %>"><%= person.first_name %> <%= person.last_name %>  </a></div>
          <span class="question-text a" ><%= person.status %> </span>
          <br/><br>
          <a href="/<%= I18n.locale %>/search/<%= person.group %>"> <span class="question-text a"><%= person.group %> </span> </a>
          <div class="row">
            <div class="col-5 a">
            </div>
            <% if @_current %>
            <div class="nrav">
              <%= link_to image_tag(image_path('сердце3.svg'), class: "mini"), main_add_path(params: { kogo:person.id }), remote: true, id: "add_#{person.id}"%>
              <%= link_to  image_tag(image_path('разбито1.jpg'), class: "mini2"), main_delete_path(params: {  kogo:person.id }), remote: true,  id: "dis_#{person.id}", class: "mini_a"%>
              <a href="../<%= I18n.locale %>/likers/<%= person.id %>"><span id="like_<%= person.id %>" class="number_like"><%= UserCommunication.where(like: person.id).count %></span></a>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <% end %>
    <%end %>
  </div>
</div>

app/views/main/likers.html.erb
<div class="container">
  <div id="main">
    <header class="hea">
      <nav class="navbar navbar-expand-md fixed-top">
        <img id="logo" src="/assets/сердце3.svg">
        <a class="navbar-brand text-dark site_name" href="../../<%= I18n.locale %>/">VBomonke</a>
        <div class="collapse navbar-collapse" id="navbarCollapse">
        </div >
        <div id="but">
          <a href= "../../<%= I18n.locale %>/main/my_profile"> <button type="button" class="btn btn-outline-secondary"><%=t 'my_profile'%><%= @_current.last_name %></button></a>
        </div>
      </nav>
    </header>
    <% if @persons.length==0 %>
    <span id="new"><%=t 'no_likers'%><%= @user.first_name %> <%= @user.last_name %></span>
    <% else %>
    <span id="new"><%=t 'likers'%><%= @user.first_name %> <%= @user.last_name %></span>
    <% end %>
    <%= render 'main/ list' %>
  </div>
</div>

app/views/main/love_users.html.erb
<div class="container">
  <div id="main">
    <header class="hea">
      <nav class="navbar navbar-expand-md fixed-top">
        <img id="logo" src="/assets/сердце3.svg">
        <a class="navbar-brand text-dark site_name" href="../<%= I18n.locale %>/">VBomonke</a>
        <div class="collapse navbar-collapse" id="navbarCollapse">
        </div >
        <div id="but">
          <a href= "../<%= I18n.locale %>/main/my_profile"> <button type="button" class="btn btn-outline-secondary"><%=t 'back'%></button></a>
        </div>
      </nav>
    </header>
    <% if @all_users.length == 0 %>
    <span id="new"><%=t 'sorry'%></span>
    <% else %>
    <span id="new"><%=t 'nice'%></span>
    <% end %>
    <% @all_users.each do |person| %>
      <% if person %>
    <div id="<%= person.id %>" class="col-9 ">
      <div class="row question-box">
        <div class="col-3 a">
          <% if person.avatar.file.nil?%>
          <img src="/assets/def_avatar.jpg" class="question-img"alt="Аватар">
          <% else %>
          <%= image_tag person.avatar.url, :class => "question-img", :alt => "Аватар"%>
          <% end %>
        </div>
        <div class="col-9 a">
          <div class="question-title a"><a class="text-dark" href="../<%= I18n.locale %>/profile/<%= person.id %>"><%= person.first_name %> <%= person.last_name %>  </a>
            <% if  UserCommunication.find_by_like_and_liker(@_current.id, person.id) %>
            <%= image_tag(image_path('звезда2.png'), class: "mini_star", title: t('mutually'))%>
            <% end %>
          </div>
          <span class="question-text a" ><%= person.status %> </span>
          <br/><br>
          <a href="/<%= I18n.locale %>/search/<%= person.group %>"> <span class="question-text a"><%= person.group %> </span> </a>
          <div class="row">
            <div class="col-5 a">
            </div>
            <div class="nrav">
              <%= link_to  image_tag(image_path('разбито1.jpg'), class: "mini_del"), main_delete_card_path(params: { kto:@_current.id, kogo:person.id }), remote: true, id: "dis_#{person.id}", data: { confirm: t('confirm') } %>
              <a href="../<%= I18n.locale %>/likers/<%= person.id %>"><span id="like_<%= person.id %>" class="number_like"><%= UserCommunication.where(like: person.id).count %></span></a>
            </div>
          </div>
        </div>
      </div>
    </div>
        <% end %>
    <%end %>
  </div>
</div>

app/views/main/my_profile.html.erb
<header class="hea">
  <nav class="navbar navbar-expand-md fixed-top">
    <img id="logo" src="/assets/сердце3.svg">
    <a class="navbar-brand text-dark site_name" href="../../<%= I18n.locale%>/">VBomonke</a>
    <div class="collapse navbar-collapse" id="navbarCollapse">
    </div >
    <div id="but">
      <a href="../records/<%= @_current.id %>"><button type="button" class="btn btn-outline-secondary"><%=t 'wall'%></button></a>
      <a href="../signout"><button type="button" class="btn btn-outline-secondary"><%=t 'output'%></button></a>
    </div>
  </nav>
</header>
<div class="container prof">
  <div id="main">
    <div class="row" id="real-estates-detail">
      <div class="col-lg-4 col-md-4 col-xs-12">
        <div class="panel panel-default">
          <div class="panel-heading">
            <header class="panel-title">
              <div class="text-center">
              </div>
            </header>
          </div>
          <div class="panel-body">
            <div class="text-center" id="author">
              <% if  @_current.avatar.file.nil?%>
              <img src="/assets/def_avatar.jpg">
              <% else %>
              <%= image_tag @_current.avatar.url%>
              <% end %>
              <% if !@_current.status.nil? && !@_current.status.empty? %>
              <h5><%= @_current.status %></h5>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-8 col-md-8 col-xs-12">
        <div class="panel">
          <div class="panel-body">
            <h1  data-toggle="tab"><%=t 'Hello'%>, <%= @_current.first_name %>   <%= @_current.last_name %> </h1>
            <div id="myTabContent" class="tab-content">
              <hr>
              <table class="table table-th-block">
                <tbody>
                  <% key=0 %>
                  <% if !@_current.group.nil? && !@_current.group.empty? %>
                  <tr><td class="active"><%=t 'group'%></td><td><a href="/<%= I18n.locale %>/search/<%= @_current.group %>"> <%= @_current.group %></a> </td></tr>
                  <%key+=1 %>
                  <% end %>
                  <% if  !@_current.city.nil? && !@_current.city.empty? %>
                  <tr><td class="active"><%=t 'country'%>:</td><td><%= @_current.city %> </td></tr>
                  <%key+=1 %>
                  <% end %>
                  <% if  !@_current.town.nil? && !@_current.town.empty? %>
                  <tr><td class="active"><%=t 'town'%></td><td><%= @_current.town %> </td></tr>
                  <%key+=1 %>
                  <% end %>
                  <% if  !@_current.born.to_s.nil? && !@_current.born.to_s.empty? %>
                  <tr><td class="active"><%=t 'born'%></td><td><%= @_current.born %></td></tr>
                  <%key+=1 %>
                  <% end %>
                  <% if !@_current.love_status.nil? && !@_current.love_status.empty? %>
                  <tr><td class="active"><%=t 'status'%>:</td><td><%= @_current.love_status %></td></tr>
                  <%key+=1 %>
                  <% end %>
                  <% if  !@_current.contact.nil? && !@_current.contact.empty? %>
                  <tr><td class="active"><%=t 'contact'%></td><td><a href="<%= @_current.contact %>" target="_blank"><%=t 'ssil'%></a> </td></tr>
                  <%key+=1 %>
                  <% end %>
                  <% if  !@_current.info.nil? && !@_current.info.empty? %>
                  <tr><td class="active"><%=t 'about'%></td><td><%= @_current.info %> </td></tr>
                  <%key+=1 %>
                  <% end %>
                </tbody>
              </table>
              <% if key<7 %>
              <br><br>
              <h6 class="zam"><%=t 'zam'%></h6>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="prof_but">
    <a href="../main/edit"> <button class="btn btn-outline-secondary" ><%=t 'edit'%></button></a>
    <a href="../love"><button class="btn btn-outline-secondary" ><%=t 'love_users'%></button></a>
  </div>
</div>
</div>

app/views/main/profile.html.erb
<header class="hea">
  <nav class="navbar navbar-expand-md fixed-top">
    <img id="logo" src="/assets/сердце3.svg">
    <a class="navbar-brand text-dark site_name" href="../../<%= I18n.locale %>/">VBomonke</a>
    <div class="collapse navbar-collapse" id="navbarCollapse">
    </div >
    <div id="but">
      <a href="../records/<%= @man.id %>"><button type="button" class="btn btn-outline-secondary"><%=t 'wall'%></button></a>
    </div>
  </nav>
</header>
<div class="container prof">
  <div id="main">
    <div class="row" id="real-estates-detail">
      <div class="col-lg-4 col-md-4 col-xs-12">
        <div class="panel panel-default">
          <div class="panel-heading">
            <header class="panel-title">
              <div class="text-center">
              </div>
            </header>
          </div>
          <div class="panel-body">
            <div class="text-center" id="author">
              <% if  @man.avatar.file.nil?%>
              <img src="/assets/def_avatar.jpg">
              <% else %>
              <%= image_tag @man.avatar.url%>
              <% end %>
              <% if !@man.status.nil? && !@man.status.empty? %>
              <h5><%= @man.status %></h5>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-8 col-md-8 col-xs-12">
        <div class="panel">
          <div class="panel-body">
            <h1  data-toggle="tab"><%= @man.first_name %>  <%= @man.last_name %></h1>
            <div id="myTabContent" class="tab-content">
              <hr>
              <table class="table table-th-block">
                <tbody>
                  <% key=0 %>
                  <% if !@man.group.nil? && !@man.group.empty? %>
                  <tr><td class="active"><%=t 'group'%></td><td><a href="/<%= I18n.locale %>/search/<%= @man.group %>"> <%= @man.group %></a> </td></tr>
                  <%key+=1 %>
                  <% end %>
                  <% if !@man.city.nil? && !@man.city.empty? %>
                  <tr><td class="active"><%=t 'country'%>:</td><td><%= @man.city %> </td></tr>
                  <%key+=1 %>
                  <% end %>
                  <% if !@man.town.nil? && !@man.town.empty? %>
                  <tr><td class="active"><%=t 'town'%></td><td><%= @man.town %> </td></tr>
                  <%key+=1 %>
                  <% end %>
                  <% if !@man.born.to_s.nil? && !@man.born.to_s.empty? %>
                  <tr><td class="active"><%=t 'born'%></td><td><%= @man.born %></td></tr>
                  <%key+=1 %>
                  <% end %>
                  <% if !@man.love_status.nil? && !@man.love_status.empty? %>
                  <tr><td class="active"><%=t 'status'%>:</td><td><%= @man.love_status %></td></tr>
                  <%key+=1 %>
                  <% end %>
                  <% if !@man.contact.nil? && !@man.contact.empty? %>
                  <tr><td class="active"><%=t 'contact'%></td><td><a href="<%= @man.contact %>" target="_blank"><%=t 'ssil'%></a> </td></tr>
                  <%key+=1 %>
                  <% end %>
                  <% if !@man.info.nil? && !@man.info.empty? %>
                  <%key+=1 %>
                  <tr><td class="active"><%=t 'about'%></td><td><%= @man.info %> </td></tr>
                  <% end %>
                </tbody>
              </table>
              <% if key<4 %>
              <br><br>
              <h6 class="zam"><%=t 'zam_prof'%></h6>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <% if UserCommunication.find_by_liker_and_like(@_current.id, @man.id) %>
  <%= link_to image_tag(image_path('сердце3.svg'), class: "mini"), main_add_path(params: { kto:@_current.id, kogo:@man.id }), remote: true, id: "add_#{@man.id}", class: "mini_a"%>
  <%= link_to  image_tag(image_path('разбито1.jpg'), class: "mini2"), main_delete_path(params: { kto:@_current.id, kogo:@man.id }), remote: true,  id: "dis_#{@man.id}"%>
  <% else %>
  <%= link_to image_tag(image_path('сердце3.svg'), class: "mini"), main_add_path(params: { kto:@_current.id, kogo:@man.id }), remote: true, id: "add_#{@man.id}"%>
  <%= link_to  image_tag(image_path('разбито1.jpg'), class: "mini2"), main_delete_path(params: { kto:@_current.id, kogo:@man.id }), remote: true,  id: "dis_#{@man.id}", class: "mini_a"%>
  <% end %>
  <a href="../likers/<%= @man.id %>"><span id="like_<%= @man.id %>" class="number_like"><%= UserCommunication.where(like: @man.id).count %></span></a>
</div>
</div>

app/views/main/search.html.erb
<div class="container">
  <div id="main">
    <header class="hea">
      <nav class="navbar navbar-expand-md fixed-top">
        <img id="logo" src="/assets/сердце3.svg">
        <a class="navbar-brand text-dark site_name" href="../../<%= I18n.locale %>/">VBomonke</a>
        <div class="collapse navbar-collapse" id="navbarCollapse">
        </div >
        <div id="but">
          <a href= "../faculty/<%= @group.split('-')[0] %>"> <button type="button" class="btn btn-outline-secondary"><%=t 'direction'%><%= @group.split('-')[0] %></button></a>
          <a href= "../main/my_profile"> <button type="button" class="btn btn-outline-secondary"><%=t 'my_profile'%><%= @_current.last_name %></button></a>
        </div>
      </nav>
    </header>
    <% if @persons.length==0 %>
    <span id="new"><%=t 'from_group'%> <%= @group %> <%=t 'end_mass'%></span>
    <% else %>
    <span id="new"><%=t 'group'%> <%= @group %></span>
    <% end %>
    <%= render 'main/ list' %>
  </div>
</div>