config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
  get 'session/new'
  get 'session/create'
  get 'session/destroy'
  root 'main#index'
  get 'main/index'
  get 'main/edit'
  get 'main/destroy'
  get 'main/create'
  post 'main/create'
  patch 'main/create'
  get 'profile/:id', to: 'main#profile'
  get 'likers/:id', to: 'main#likers'
  get 'search/:group', to: 'main#search'
  get 'faculty/:faculty', to: 'main#faculty'
  get 'main/my_profile'
  get 'records/:id', to: 'wall#records'
  get '/signin', to: 'session#new'
  get '/signup', to: 'users#new'
  get '/signout', to: 'session#destroy'
  get 'session/destroy'
  get 'love', to: 'main#love_users'
  get 'records/:id', to: 'wall#records'
  get '/edit_record/', to: 'wall#edit_record'
  get 'wall/delete_record'
  get 'wall/update'
  post 'wall/update'
  patch 'wall/update'
  get '/add_record', to: 'wall#add_record'
  get 'wall/create_record'
  post 'wall/create_record'
  patch 'wall/create_record'
  get 'main/add'
  get 'main/delete'
  get 'main/delete_card'

  resources :session, only: %i[new create destroy]
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
end

app/controllers/session_controller.rb
# frozen_string_literal: true

# Controller for session
class SessionController < ApplicationController
  skip_before_action :authenticate, only: %i[new create]

  def new
    @_current = User.find_by_id(session[:current_user_id])
    redirect_to main_index_path if @_current
  end

  def create
    user = User.authenticate(params[:session][:email],
                             params[:session][:password])
    if user.nil?

      redirect_to signin_url, alert: t('no_login')

    else
      sign_in user
      redirect_to main_index_path
    end
  end

  def destroy
    sign_out
    redirect_to signin_url
  end
end

app/helpers/session_helper.rb
# frozen_string_literal: true

# for authorization
module SessionHelper
  def sign_in(user)
    session[:current_user_id] = user.id
    self.current_user = user
  end

  def sign_out
    session[:current_user_id] = nil
    self.current_user = nil
  end

  def current_user=(user)
    @current_user = user
  end
end

app/views/session/new.html.erb
<div  class ="sign_form">
  <%= form_for(:session, :url => session_index_path,:html => {:class => 'form-sign'} ) do |f| %>
    <h1 class="vb"> <img id="logo" src="/assets/сердце3.svg" /><a href="../<%= I18n.locale %>/">VBomonke</a></h1>
    <br/>
  <%= @title%>
  <p id="alert"><%= alert %></p>
  <%= f.email_field :email, :class => 'form-control inp',:placeholder => t('email')%>
  <%= f.password_field :password, :class => 'form-control inp psr',:placeholder => t('pass')%>
  <div class="actions">
    <%= f.submit t('entry_but'), :class => 'btn btn-outline-secondary'%>
  </div>
  <span class="link_to_s"><%=t 'New_user?'%></span>
  <%= link_to t('will_reg'), signup_path %>
  <% end %>
</div>