config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
  get 'session/new'
  get 'session/create'
  get 'session/destroy'
  root 'main#index'
  get 'main/index'
  get 'main/edit'
  get 'main/destroy'
  get 'main/create'
  post 'main/create'
  patch 'main/create'
  get 'profile/:id', to: 'main#profile'
  get 'likers/:id', to: 'main#likers'
  get 'search/:group', to: 'main#search'
  get 'faculty/:faculty', to: 'main#faculty'
  get 'main/my_profile'
  get 'records/:id', to: 'wall#records'
  get '/signin', to: 'session#new'
  get '/signup', to: 'users#new'
  get '/signout', to: 'session#destroy'
  get 'session/destroy'
  get 'love', to: 'main#love_users'
  get 'records/:id', to: 'wall#records'
  get '/edit_record/', to: 'wall#edit_record'
  get 'wall/delete_record'
  get 'wall/update'
  post 'wall/update'
  patch 'wall/update'
  get '/add_record', to: 'wall#add_record'
  get 'wall/create_record'
  post 'wall/create_record'
  patch 'wall/create_record'
  get 'main/add'
  get 'main/delete'
  get 'main/delete_card'

  resources :session, only: %i[new create destroy]
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
end

app/models/user.rb
# frozen_string_literal: true

# Model for user
class User < ApplicationRecord
  has_secure_password
  validates :email, presence: true, uniqueness: true
  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  validates :first_name, presence: true, length: { maximum: 30 }
  validates :last_name, presence: true,  length: { maximum: 18 }
  validates :password, confirmation: true, length: { minimum: 6 }, if: -> { new_record? || !password.nil? }
  validates :status, length: { maximum: 50 }
  validates :info, length: { maximum: 500 }
  validates :city,  length: { maximum: 30 }
  validates :town,  length: { maximum: 30 }
  validates :love_status, length: { maximum: 30 }
  validates_format_of :contact, with: /(^\s*$)|(https:\/\/vk.com\/)/, message: I18n.t(:contact_message)
  validates_format_of :group, with: /(^\s*$)|(\A((ИУ)|(IU)|(СМ)|(SM)|(МТ)|(MT)|(РК)|(RK)|(СГН)|(SGN)|(БМТ)|(BMT)|(ИБМ)|(IBM)|(АК)|(AK)|(ИСОТ)|(ISOT)|(ОЭ)|(OE)|(РКТ)|(RKT)|(РТ)|(RT)|(Э)|(E)|(ЮР)|(YR)|(ФН)|(FN)|(РЛ)|(RL))((1[0-2])|[1-9])-((1[0-2])|[1-9])[1-9](А|Б|М|A|B|M)?\Z)/, message: I18n.t(:group_message)
  mount_uploader :avatar, AvatarUploader


  def self.authenticate(email, submitted_password)
    user = find_by(email: email)
    return nil if user.nil?
    return user if user.authenticate(submitted_password)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# Controller for signup
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  def index
    redirect_to signup_path
  end

  def new
    @_current = User.find_by_id(session[:current_user_id])
    redirect_to main_index_path if @_current
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to session_new_path
    else
      render :new

    end
  end


  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :password, :first_name, :last_name, :password_confirmation)
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/users/new.html.erb
<div  class ="sign_form">
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%=t 'from_being_saved'%> </h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form_with(model: @user, local: true, :class => 'form-signin' ) do |form| %>
      <h1 class="vb"> <img id="logo" src="/assets/сердце3.svg" /><a href="../<%= I18n.locale %>/">VBomonke</a></h1><br/>
      <%= form.email_field :email, :class => 'form-control inp',:placeholder => t('email')%>
      <%= form.password_field :password, :class => 'form-control inp psr',:placeholder => t('pass')%>
      <%= form.password_field :password_confirmation, :class => 'form-control inp psr',:placeholder => t('pass_rep')%>
      <%= form.text_field :first_name, :class => 'form-control inp em',:placeholder => t('sername')%>
      <%= form.text_field :last_name, :class => 'form-control inp' ,:placeholder => t('name')%>
      <div class="actions">
        <%= form.submit t('reg_but'), :class => 'btn btn-outline-secondary'   %>
      </div>
      <span class="link_to_sign"><%=t 'Already_has_account?'%></span>
      <%= link_to t('entry_but'),  signin_path %>
    <% end %>
  </div>
</div>