config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
  get 'session/new'
  get 'session/create'
  get 'session/destroy'
  root 'main#index'
  get 'main/index'
  get 'main/edit'
  get 'main/destroy'
  get 'main/create'
  post 'main/create'
  patch 'main/create'
  get 'profile/:id', to: 'main#profile'
  get 'likers/:id', to: 'main#likers'
  get 'search/:group', to: 'main#search'
  get 'faculty/:faculty', to: 'main#faculty'
  get 'main/my_profile'
  get 'records/:id', to: 'wall#records'
  get '/signin', to: 'session#new'
  get '/signup', to: 'users#new'
  get '/signout', to: 'session#destroy'
  get 'session/destroy'
  get 'love', to: 'main#love_users'
  get 'records/:id', to: 'wall#records'
  get '/edit_record/', to: 'wall#edit_record'
  get 'wall/delete_record'
  get 'wall/update'
  post 'wall/update'
  patch 'wall/update'
  get '/add_record', to: 'wall#add_record'
  get 'wall/create_record'
  post 'wall/create_record'
  patch 'wall/create_record'
  get 'main/add'
  get 'main/delete'
  get 'main/delete_card'

  resources :session, only: %i[new create destroy]
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
end

app/models/wall.rb
# frozen_string_literal: true

# Model for records
class Wall < ApplicationRecord
end

app/controllers/wall_controller.rb
# frozen_string_literal: true

# Model wall
class WallController < ApplicationController
  before_action :set_user, only: %i[records add_record create_record update edit_record]
  def records
    @id = params[:id].to_i
    if @id.to_s =~ /\A[0-9]+\Z/
      @records = Wall.where(author: @id).order(:id).reverse_order
      @author = User.find_by_id(@id)
    else
      render :error
    end

  end

  def add_record
    @record = Wall.new
  end

  def create_record
    current_user
    @new_record = Wall.new(record_params)
    @new_record.author = @_current.id
    if @new_record.save
      redirect_to "/#{I18n.locale}/records/#{@_current.id}"
    else
      render :add_record

    end
  end

  def delete_record
    @id = params[:id]
    record_to_delete = Wall.find_by_id(@id)
    record_to_delete.destroy
    respond_to do |format|
      format.js
    end
  end

  def edit_record
    @id = params[:id]
    @edit_record = Wall.find_by_id(@id)
  end

  def update
    if !request.get?
      if Wall.find(params[:id]).update(record_params)
        redirect_to "/#{I18n.locale}/records/#{@_current.id}"
      else
        render :edit_record
      end
    else redirect_to edit_record_path
    end
  end

  private

  def set_user
    @_current = User.find_by_id(session[:current_user_id])
  end

  def record_params
    params.require(:wall).permit(:title, :body, :status)
  end
end

app/helpers/wall_helper.rb
module WallHelper
end

app/views/wall/add_record.html.erb
<body class="wall">
<div  class ="sign_form">
  <% if @record.errors.any? %>
    <div id="error_explanation">
      <h2><%=t 'from_being_saved'%> </h2>
      <ul>
        <% @record.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <%= form_with(model: @record, url: wall_create_record_path ,local: true, :class => 'form-signin' ) do |form| %>
      <h1 class="vb">&nbsp;&nbsp;<%=t 'new_rec'%></h1><br/>
      <%= form.text_field :title, :class => 'form-control inp',:placeholder => t('title_rec')%>
      <%= form.text_area :body, :class => 'form-control inp' ,:placeholder => t('thinks')  %>
    <div class="form-control inp" > <%= form.select :status, [t('tag_one'), t('tag_two'), t('tag_tree')] , :class => 'form-control inp' %> </div>
      <div class="actions">
        <%= form.submit t('creat'), :class => 'btn btn-outline-secondary'   %>
      </div>
      <span class="link_to_sign"><%=t 'rethink'%></span>
      <%= link_to t('back_rec'),  "/#{I18n.locale}/records/#{@_current.id}" %>
    <% end %>
  </div>
</div>
</body>

app/views/wall/delete_record.js.erb
elem_to_del = document.getElementById('<%= @id %>')
elem_to_del.remove()

app/views/wall/edit_record.html.erb
<body class="wall">
<div  class ="sign_form">
  <% if @edit_record %>
  <% if @edit_record.errors.any? %>
    <div id="error_explanation">
      <h2> <%=t 'from_being_saved'%> </h2>
      <ul>
        <% @edit_record.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
    <% end %>
  <%=  form_with(model:@edit_record,  local: true, url: wall_update_path(id: @edit_record.id), :class => 'form-signin') do |form|%>
    <h1 class="vb"><%=t 'change_rec'%></h1><br/>
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <%= form.text_field :title, :class => 'form-control inp',:placeholder => t('title_rec')%>
    <%= form.text_area :body, :class => 'form-control inp' ,:placeholder => t('thinks') %>
    <div class="form-control inp" > <%= form.select :status, [t('tag_one'), t('tag_two'), t('tag_tree')] , :class => 'form-control inp' %> </div>
    <%= form.submit t('edit_link'), :class => 'btn btn-outline-secondary'   %>
    <span class="link_to_sign"><%=t 'rethink'%></span>
    <%= link_to t('back_rec'), "/#{I18n.locale}/records/#{@_current.id}" %>
    <br><br>
  <% end %>
</div>
</body>

app/views/wall/error.html.erb
<body class="wall"><span>ТЫ ЧТО БАЛУЕШЬСЯ, ДУРАЧОК</span></body>

app/views/wall/records.html.erb
<body class="wall">
<div class="container">
  <div id="main">
    <header class="hea">
      <nav class="navbar navbar-expand-md fixed-top">
        <img id="logo" src="/assets/сердце3.svg">
        <a class="navbar-brand text-dark site_name" href="../../<%= I18n.locale %>/">VBomonke</a>
        <div class="collapse navbar-collapse" id="navbarCollapse">
        </div >
        <div id="but">
          <% if @_current.id == @id %>
            <a href= "../../<%= I18n.locale %>/main/my_profile"> <button type="button" class="btn btn-outline-secondary"><%=t 'back'%></button></a>
            <a href="../add_record"><button type="button" id="exit" class="btn btn-outline-secondary"><%=t 'create_rec'%></button></a>
            <% else %>
            <a href= "../profile/<%= @id %>"> <button type="button" class="btn btn-outline-secondary"><%=t 'back'%></button></a>
            <% end %>
        </div>
      </nav>
    </header>
    <% if @records.length==0 %>
      <span id="new"><%=t 'new_mess'%></span>
    <% else %>
      <% if @_current.id == @id %>
        <span id="new_2"><%=t 'your_wall'%> , <%= @author.first_name %> <%= @author.last_name %></span>
      <% else %>
      <span id="new"><%=t 'new_mess_true'%> <%= @author.first_name %> <%= @author.last_name %></span>
      <% end %>
    <% end %>
    <% @records.each do |record| %>
      <div id="<%= record.id %>" class="col-9 ">
          <div class="row question-box">
            <div class="col a">
              <div class="question-title a"><%= record.title %>
                <% if record.status == t('tag_one') %>
                <%= image_tag(image_path('мозг.png'), class: "mini", title: t('tag_one')) %>
                  <% elsif record.status == t('tag_two')%>
                  <%= image_tag(image_path('нравится.jpg'), class: "mini", title: t('tag_two')) %>
                <% else %>
                  <%= image_tag(image_path('не_нравится.jpg'), class: "mini", title: t('tag_tree')) %>
                <% end %>
              </div>
              <span class="question-text a" ><%= record.body %> </span>
              <br/><br>
                <% if @_current.id == @id %>
                  <div class="nrav">
                    <%= link_to image_tag(image_path('настройки.jpg'), class: "mini"), edit_record_path(params: { id: record.id }), class: "edit"%>
                    <%= link_to  image_tag(image_path('корзина.jpg'), class: "mini2"), wall_delete_record_path(params: { id: record.id }), remote: true,  id: "dis_#{record.id}", data: { confirm: t('confirm_wall') } %>
                  </div>
                <% end %>
              </div>
          </div>
        </div>
    <%end %>
  </div>
</div>
</body>